server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;
    server_tokens off;

    location = /favicon.ico {
        default_type image/x-icon;
        return 204;
        access_log off;
    }

    location = /123.rar {
        alias /usr/share/nginx/html/123.rar;
        default_type application/octet-stream;
        add_header X-Content-Type-Options nosniff;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name _;

    ssl_certificate     /etc/nginx/ssl/stub.crt;
    ssl_certificate_key /etc/nginx/ssl/stub.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;
    server_tokens off;

    location = /favicon.ico {
        default_type image/x-icon;
        return 204;
        access_log off;
    }

    location = /123.rar {
        alias /usr/share/nginx/html/123.rar;
        default_type application/octet-stream;
        add_header X-Content-Type-Options nosniff;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
